### ISSUE TITLE
Port 80 is occupied by a nginx to do, I hope I can point to any one domain name

### ISSUE THREAD

**Issue by guoyoujin** [meteorhacks/meteord#62]
Port 80 is occupied by a nginx to do, I hope I can point to any one domain name

**Comment by jshimko** [comment]
?

Not clear what the issue is here.  Port allocation is the responsibility of the user.  I don't think this is an issue with this repo.  The Dockerfile exposes port 80, but it doesn't force you to open that port on the docker host.  You could easily choose another port (eg. `-p 8080:80`).  Or just link an NGINX proxy container without opening the app container to the host (see [`jwilder/nginx-proxy`](https://hub.docker.com/r/jwilder/nginx-proxy/)).

**Comment by arunoda** [comment]
Yep. Post allocation is upto you.
