### ISSUE TITLE
Should I not .gitignore the node_modules directory?

### ISSUE THREAD

**Issue by krishamoud** [meteorhacks/meteord#93]
I just started using meteor 1.3 and I built an app here https://github.com/krishamoud/asteroidbelt which is gitignoreing `node_modules` and the `settings.json` file.  When I run meteord locally with the `node_modules` already installed then everything is fine and it builds the same as it always has.  When I do a remote build it fails and tells me that there are unresolved imports.  Specifically `react`.

Is this expected behavior?

**Comment by jshimko** [comment]
That is unfortunately the expected behavior with the current version of meteord.  It's because `npm install` is not being run before `meteor build` inside the container (needs to happen [right here](https://github.com/meteorhacks/meteord/blob/master/base/scripts/lib/build_app.sh#L10)).  If you don't already have the `node_modules` folder in your source, it won't end up being created in the container.  It's not a problem if you build locally from your dev setup, but a build from a fresh `git clone` will not work. 

This has been [discussed recently](https://github.com/meteorhacks/meteord/issues/90) and I personally think we should be adding `npm install --production` to the build script.  But not everyone agrees, so I guess everyone is just going to have to do what works for their project.  In my case, I [forked meteord](https://github.com/jshimko/meteord/tree/meteor-one-three) and added that line to the build script because I need CircleCI to be able to build my images from a `git clone`.  I also could have added an `npm install` to my CI config right before the `docker build`, but the whole point of Docker (to me) is to have builds work the exact same way regardless of where they're run.

If you want what the changes described above, feel free to use my repo (`meteor-one-three` branch) 
https://github.com/jshimko/meteord/tree/meteor-one-three

Or you can just use the image I built from that by adding this to your Dockerfile...

``` Dockerfile
FROM jshimko/meteord:onbuild
```

(`devbuild` and `binbuild` will work too)

And to answer your original question... no, you definitely don't want to commit `node_modules` to your repo.  Add `FROM jshimko/meteord:onbuild` to your Dockerfile and you won't have to.  ;)

**Comment by krishamoud** [comment]
Great!  Thanks for the reply!  I'll definitely be using your image for my project.  Is it backwards compatible with meteor version pre-1.3?

**Comment by jshimko** [comment]
Well, it depends.  The only functionality change is the `npm install`, so it shouldn't effect anything other than that.  However, running `npm install` in a directory without a package.json will definitely throw an error (which will likely tank the build).  So that said, you could just continue using the official meteord for Meteor versions before 1.3 that don't make use of app level NPM packages.

Now that you mention it, I could've made that conditional so it only runs when a package.json is present.  Give me a few and I'll update it.

**Comment by jshimko** [comment]
[All set](https://github.com/jshimko/meteord/commit/71e14ea877d4a1c2c4a3c4263ddc0ce97e5d7a52).  Now it'll only run `npm install` if your app has a package.json in the root.

**Comment by krishamoud** [comment]
Thanks for the quick replies!  This is great!
